name: happy_family
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  get_storage: ^2.0.3
  datetime_picker_formfield: ^2.0.1
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: ^3.0.0
  lottie: ^1.3.0
  cloud_firestore: ^4.5.0
  fluttertoast: ^8.2.1
  firebase_messaging: ^14.4.0
  http: ^0.13.6
  flutter_local_notifications: ^14.0.0+1

  flutter: 
    sdk: flutter



dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

dependency_overrides: 
  firebase_core_platform_interface: 4.6.0

flutter: 
  uses-material-design: true

  assets:
    - assets/lotties/
    - assets/logo/
